#include "output.h"
#include <cstdio>
#include <cstring>
#include <stdexcept>

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
static FILE* open_or_die(const std::string& path, const char* mode) {
    if (path == "-")
        return (mode[0] == 'w') ? stdout : stdin;
    FILE* f = fopen(path.c_str(), mode);
    if (!f) {
        fprintf(stderr, "error: cannot open '%s': ", path.c_str());
        perror(nullptr);
        exit(1);
    }
    return f;
}

// Write a 32-bit word as little-endian bytes
static void push_le32(std::vector<uint8_t>& buf, uint32_t word) {
    buf.push_back((uint8_t)(word >>  0));
    buf.push_back((uint8_t)(word >>  8));
    buf.push_back((uint8_t)(word >> 16));
    buf.push_back((uint8_t)(word >> 24));
}

// ---------------------------------------------------------------------------
// build_image
// Iterates entries in address order, zero-fills gaps.
// ---------------------------------------------------------------------------
FlatImage build_image(const std::vector<SectionEntry>& entries,
                      uint32_t base_addr) {
    FlatImage img;
    img.base_addr = base_addr;

    for (const SectionEntry& e : entries) {
        // Ensure the buffer is large enough to reach e.byte_addr
        uint32_t offset = e.byte_addr - base_addr;
        if (offset > img.bytes.size()) {
            // Zero-fill the gap
            img.bytes.resize(offset, 0x00);
        }

        if (e.kind == SectionEntry::Kind::INST) {
            uint32_t word = encode(e.inst);
            push_le32(img.bytes, word);
        } else {
            // DATA
            const DataItem& d = e.data;
            switch (d.kind) {
                case DataItem::Kind::WORD:
                    push_le32(img.bytes, d.value);
                    break;
                case DataItem::Kind::BYTE:
                    img.bytes.push_back((uint8_t)(d.value & 0xFF));
                    break;
                case DataItem::Kind::SPACE:
                    for (uint32_t i = 0; i < d.count; ++i)
                        img.bytes.push_back(0x00);
                    break;
            }
        }
    }

    return img;
}

// ---------------------------------------------------------------------------
// write_output — dispatch to format-specific writer
// ---------------------------------------------------------------------------
static void write_bin(const FlatImage& img, FILE* f) {
    fwrite(img.bytes.data(), 1, img.bytes.size(), f);
}

// Intel HEX — standard 16-byte data records + EOF record
static void write_intel_hex(const FlatImage& img, FILE* f) {
    const uint8_t* data  = img.bytes.data();
    uint32_t       total = img.bytes.size();
    uint32_t       addr  = img.base_addr;
    uint32_t       off   = 0;

    // Emit Extended Linear Address record if base >= 64KB
    if (addr >> 16) {
        uint16_t upper = (uint16_t)(addr >> 16);
        uint8_t  chk   = (uint8_t)(-(2 + 0 + 4 + (upper>>8) + (upper&0xFF)));
        fprintf(f, ":02000004%04X%02X\n", upper, (unsigned)(chk & 0xFF));
    }

    while (off < total) {
        uint32_t chunk = total - off;
        if (chunk > 16) chunk = 16;

        uint32_t rec_addr = addr + off;

        // Recalculate extended address record when crossing 64KB boundary
        if (off > 0 && (rec_addr >> 16) != ((rec_addr - chunk) >> 16)) {
            uint16_t upper = (uint16_t)(rec_addr >> 16);
            uint8_t  chk   = (uint8_t)(-(2 + 0 + 4 + (upper>>8) + (upper&0xFF)));
            fprintf(f, ":02000004%04X%02X\n", upper, (unsigned)(chk & 0xFF));
        }

        fprintf(f, ":%02X%04X00", chunk, rec_addr & 0xFFFF);
        uint8_t sum = (uint8_t)chunk + (uint8_t)(rec_addr >> 8) + (uint8_t)rec_addr;
        for (uint32_t i = 0; i < chunk; ++i) {
            fprintf(f, "%02X", data[off + i]);
            sum += data[off + i];
        }
        fprintf(f, "%02X\n", (unsigned)((uint8_t)(~sum + 1)));
        off += chunk;
    }
    fprintf(f, ":00000001FF\n");
}

// Xilinx .coe — one 32-bit hex value per line, little-endian words
// memory_initialization_radix=16;
// memory_initialization_vector=WORD0, WORD1, ...;
static void write_coe(const FlatImage& img, FILE* f) {
    fprintf(f, "; Generated by legv8-as\n");
    fprintf(f, "; Base address: 0x%08X  Size: %u bytes\n",
            img.base_addr, img.size());
    fprintf(f, "memory_initialization_radix=16;\n");
    fprintf(f, "memory_initialization_vector=\n");

    const uint8_t* data  = img.bytes.data();
    uint32_t       total = img.bytes.size();

    // Pad to word boundary
    uint32_t words = (total + 3) / 4;

    for (uint32_t w = 0; w < words; ++w) {
        uint32_t off  = w * 4;
        uint32_t word = 0;
        // Little-endian reconstruction
        for (int b = 0; b < 4 && off+b < total; ++b)
            word |= (uint32_t)data[off+b] << (b * 8);
        bool last = (w == words - 1);
        fprintf(f, "%08X%s\n", word, last ? ";" : ",");
    }
}

void write_output(const FlatImage& img, const std::string& path,
                  OutputFormat fmt) {
    const char* mode = (fmt == OutputFormat::BIN) ? "wb" : "w";
    FILE* f = open_or_die(path, mode);

    switch (fmt) {
        case OutputFormat::BIN:        write_bin(img, f);        break;
        case OutputFormat::HEX_INTEL:  write_intel_hex(img, f);  break;
        case OutputFormat::COE:        write_coe(img, f);        break;
        case OutputFormat::LISTING:    /* handled separately */   break;
    }

    if (f != stdout) fclose(f);
}

// ---------------------------------------------------------------------------
// write_listing — human-readable: addr | hex | mnemonic
// ---------------------------------------------------------------------------
void write_listing(const std::vector<SectionEntry>& entries,
                   const std::string& path) {
    FILE* f = open_or_die(path, "w");

    fprintf(f, "%-10s  %-10s  %s\n", "Addr", "Encoding", "Source");
    fprintf(f, "%-10s  %-10s  %s\n",
            "----------", "----------", "-----------");

    for (const SectionEntry& e : entries) {
        if (e.kind == SectionEntry::Kind::INST) {
            uint32_t word = encode(e.inst);
            fprintf(f, "0x%08X  0x%08X  %s\n",
                    e.byte_addr, word, e.inst.mnemonic.c_str());
        } else {
            const DataItem& d = e.data;
            switch (d.kind) {
                case DataItem::Kind::WORD:
                    fprintf(f, "0x%08X  0x%08X  .word\n",
                            e.byte_addr, d.value);
                    break;
                case DataItem::Kind::BYTE:
                    fprintf(f, "0x%08X  0x%02X        .byte\n",
                            e.byte_addr, d.value);
                    break;
                case DataItem::Kind::SPACE:
                    fprintf(f, "0x%08X  [%-8u]  .space\n",
                            e.byte_addr, d.count);
                    break;
            }
        }
    }

    if (f != stdout) fclose(f);
}
